version: '3.8'

services:
  localstack:
    image: localstack/localstack:3.4.0
    container_name: cs2-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,sqs
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./.localstack:/var/lib/localstack"

  redis:
    image: redis:alpine
    container_name: cs2-redis
    ports:
      - "6379:6379"
