spring:
  application:
    name: cs2-processor
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        use-default-aws-credentials-chain: true
      endpoint: ${AWS_ENDPOINT_URL:#{null}}

app:
  sqs:
    queue-url: ${SQS_QUEUE_URL}

aws:
  region: ${AWS_REGION:us-east-1}
  endpoint-url: ${AWS_ENDPOINT_URL:#{null}}
